services:
  php:
    build:
      context: docker/php
    restart: always
    expose:
      - ${PHP_PORT}
    working_dir: ${APP_PATH}
    user: ${UID}:${GID}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}
    depends_on:
      - db
    links:
      - db:${POSTGRES_HOST}

  nginx:
    image: nginx:1.27.4
    command: /bin/bash -c "envsubst '$$NGINX_ROOT $$PHP_HOST $$PHP_PORT' < /etc/nginx/site.conf.tmpl > /etc/nginx/sites-available/site.conf && nginx -g 'daemon off;'"
    restart: always
    ports: 
      - ${NGINX_PORT}:80
    environment:
      - NGINX_ROOT=${APP_PATH}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
    depends_on:
      - php
    links:
      - php:${PHP_HOST}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}:ro
      - /etc/nginx/sites-available
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/site.conf.tmpl:/etc/nginx/site.conf.tmpl:ro

  db:
    image: postgres:17.4-alpine3.21
    restart: always
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  node:
    image: node:23-alpine3.20
    ports:
      - 5173:5173
    working_dir: ${APP_PATH}
    user: ${UID}:${GID}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}

  swaggerui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    restart: always
    ports:
      - ${SWAGGERUI_PORT}:80
    environment:
      - PORT=80
      - SWAGGER_JSON_URL=http://localhost:${NGINX_PORT}/api/openapi

volumes:
  db: